---
title: "<center>Statistical Learning HW4<center>"
author: "<p align='right'>105071013 陳冠維</p>>"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**10.**

**a**
```{r, echo=FALSE}
#10
#a
library(ISLR)
pairs(Weekly)
summary(Weekly)
cor(Weekly[, -9])
```

**b**
```{r, echo=FALSE}
attach(Weekly)
fit_logi <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, data = Weekly, family = binomial)
summary(fit_logi)
```

**c**
```{r, echo=FALSE}
#confusion matrix
logi_pred <- predict(fit_logi, type = "response")
logi_up_down <- ifelse(logi_pred > 0.5, "Up", "Down")
print("confusion matrix")
table(logi_up_down, Direction)
#accuracy = 0.5610652
cat('accuracy：', mean(logi_up_down == Direction))
```

**d**
```{r, echo=FALSE}
print('logistice regression')
library(ROCR)
#train test split
train <- (Year < 2009)
test <- Weekly[!train, ]
Direction_test <- Direction[!train]
#logistic
fit_logi_2 <- glm(Direction ~ Lag2, data = Weekly, family = binomial, subset = train)
logi_pred2 <- predict(fit_logi_2, test, type = "response")
pred_logit <- ifelse(logi_pred2 > 0.5, "Up", "Down")
table(pred_logit)
print('confusion matrix')
table(pred_logit, Direction_test)
#accuracy = 0.625
cat('accuracy：', mean(pred_logit == Direction_test))
#AUC
pred1 <- prediction(logi_pred2, Direction_test)
auc1 <- performance(pred1, measure = "auc")
#AUC = 0.546321
cat('AUC：', auc1@y.values[[1]])
```

**e**

**(i)**
```{r, echo=FALSE}
print('Naive Bayes')
library(e1071)
fit_nb <- naiveBayes(Direction ~ Lag2, data=Weekly, subset=train)
pred_nb <- predict(fit_nb, test)
table(pred_nb)
print('confusion matrix')
table(pred_nb, Direction_test)
#accuracy = 0.5865385
cat('accuracy：', mean(pred_nb == Direction_test))
#AUC
pred_nb2 <- predict(fit_nb, test, type = "raw")
pred2 <- prediction(pred_nb2[, 2], Direction_test)
auc2 <- performance(pred2, measure = "auc")
#AUC = 0.508578
cat('AUC：', auc2@y.values[[1]])
```

**(ii)**
```{r, echo=FALSE}
print('LDA')
library(MASS)
fit_lda <- lda(Direction ~ Lag2, data = Weekly, subset = train)
pred_lda <- predict(fit_lda, test)
table(pred_lda$class)
print('confusion matrix')
table(pred_lda$class, Direction_test)
# accuracy = 0.625
cat('accuracy：', mean(pred_lda$class == Direction_test))
#AUC
pred3 <- prediction(pred_lda$posterior[, 2], Direction_test)
auc3 <- performance(pred3, measure = "auc")
#AUC = 0.546321
cat('AUC：', auc3@y.values[[1]])
```

**f**
```{r, echo=FALSE}
print('QDA')
fit_qda <- qda(Direction ~ Lag2, data = Weekly, subset = train)
pred_qda <- predict(fit_qda, test)
table(pred_qda$class)
print('confusion matrix')
table(pred_qda$class, Direction_test)
# accuracy = 0.5865385
cat('accuracy：', mean(pred_qda$class == Direction_test))
#AUC
pred4 <- prediction(pred_qda$posterior[, 2], Direction_test)
auc4 <- performance(pred4, measure = "auc")
#AUC = 0.508578
cat('AUC：', auc4@y.values[[1]])
```

**g**
```{r, echo=FALSE}
print('KNN with K = 1')
library(class)
library(pROC)
#split data
train_X = as.matrix(Lag2[train])
test_X = as.matrix(Lag2[!train])
train_Y <- Direction[train]
#set seed
set.seed(1)
# predict when k=1
pred_knn_1 <- knn(train_X, test_X, train_Y, k=1)
table(pred_knn_1)
print('confusion matrix')
table(pred_knn_1, Direction_test)
# accuracy = 0.5
cat('accuracy：', mean(pred_knn_1 == Direction_test))
#AUC = 0.4983
cat('AUC：', auc(as.numeric(Direction_test), as.numeric(pred_knn_1)))
```

**h**

**i**
```{r, echo=FALSE}
print('logistic')
fit_logi_3 <- glm(Direction ~ sqrt(abs(Lag1)) + Lag2, data = Weekly, family = binomial, subset = train)
logi_pred3 <- predict(fit_logi_3, test, type = "response")
pred_logit3 <- ifelse(logi_pred3 > 0.5, "Up", "Down")
table(pred_logit3)
print('confusion matrix')
table(pred_logit3, Direction_test)
#accuracy = 0.625 -> 0.6346154
cat('accuracy：', mean(pred_logit3 == Direction_test))
#AUC
pred <- prediction(logi_pred3, Direction_test)
auc <- performance(pred, measure = "auc")
#AUC = 0.546321 -> 0.5390774
cat('AUC：', auc@y.values[[1]])
```

```{r, echo=FALSE}
print('Naive Bayes')
fit_nb <- naiveBayes(Direction ~ Lag1 + Lag2, data=Weekly, subset=train)
pred_nb <- predict(fit_nb, test)
table(pred_nb)
print('confusion matrix')
table(pred_nb, Direction_test)
#accuracy = 0.5865385 -> 0.5384615
cat('accuracy：', mean(pred_nb == Direction_test))
#AUC
pred_nb2 <- predict(fit_nb, test, type = "raw")
pred2 <- prediction(pred_nb2[, 2], Direction_test)
auc2 <- performance(pred2, measure = "auc")
#AUC = 0.508578 -> 0.5120091
cat('AUC：', auc2@y.values[[1]])
```

```{r, echo=FALSE}
print('LDA')
fit_lda <- lda(Direction ~ sqrt(abs(Lag1)) + Lag2, data = Weekly, subset = train)
pred_lda <- predict(fit_lda, test)
table(pred_lda$class)
print('confusion matrix')
table(pred_lda$class, Direction_test)
# accuracy = 0.625 -> 0.6346154
cat('accuracy：', mean(pred_lda$class == Direction_test))
#AUC
pred3 <- prediction(pred_lda$posterior[, 2], Direction_test)
auc3 <- performance(pred3, measure = "auc")
#AUC = 0.546321 -> 0.5398399
cat('AUC：', auc3@y.values[[1]])
```

```{r, echo=FALSE}
print('QDA')
fit_qda <- qda(Direction ~ Lag2 + sqrt(abs(Lag2)), data = Weekly, subset = train)
pred_qda <- predict(fit_qda, test)
table(pred_qda$class)
print('confusion matrix')
table(pred_qda$class, Direction_test)
# accuracy = 0.5865385 -> 0.5769231
cat('accuracy：', mean(pred_qda$class == Direction_test))
#AUC
pred4 <- prediction(pred_qda$posterior[, 2], Direction_test)
auc4 <- performance(pred4, measure = "auc")
#AUC = 0.508578 -> 0.544796
cat('AUC：', auc4@y.values[[1]])
```

```{r, echo=FALSE}
print('KNN with K = 1')
#split data
train_X <- cbind(sqrt(abs(Lag1)), Lag2)[train, ]
test_X <- cbind(Lag1, Lag2)[!train, ]
train_Y <- Direction[train]
#set seed
set.seed(1)
# predict when k=1
pred_knn_1 <- knn(train_X, test_X, train_Y, k=1)
table(pred_knn_1)
print('confusion matrix')
table(pred_knn_1, Direction_test)
# accuracy = 0.5 -> 0.5288462
cat('accuracy：', mean(pred_knn_1 == Direction_test))
#AUC = 0.4983 -> 0.5229
cat('AUC：', auc(as.numeric(Direction_test), as.numeric(pred_knn_1)))
```

```{r, echo=FALSE}
print('KNN with K = 100')
#set seed
set.seed(1)
# predict when k=1
pred_knn_1 <- knn(train_X, test_X, train_Y, k=100)
table(pred_knn_1)
print('confusion matrix')
table(pred_knn_1, Direction_test)
# accuracy = 0.5 -> 0.6346154
cat('accuracy：', mean(pred_knn_1 == Direction_test))
#AUC = 0.4983 -> 0.565
cat('AUC：', auc(as.numeric(Direction_test), as.numeric(pred_knn_1)))
```

















